---
ignores:
  - "@changesets/cli"
  - "@monodist/tsconfig"
  - "@types/eslint"
  - "@types/jest"
  - "@types/node"
  - depcheck
  - eslint
  - husky
  - jest
  - jest-standard-reporter
  - lint-staged
  - prettier
  - rimraf
  - ts-jest
  - ts-node
  - typescript
