name: master (push)

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: 12
  PNPM_VERSION: 5.5.12

jobs:
  changeset-build-test-run:
    runs-on: ubuntu-latest

    steps:
      # Begin setup
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          check-latest: true
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache pnpm-store
        id: cache-pnpm
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store
      - run: curl -L https://unpkg.com/@pnpm/self-installer | node
      - run: pnpm install
      # End setup

      # Run `prettier` before changeset
      - name: Check formatting
        run: pnpm prettier

      # Begin version
      - name: Update git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Get changeset status
        id: status
        run: |
          if pnpx changeset status 2>&1 | grep -i "no changesets present"; \
          then echo "::set-output name=changes::false"; \
          else echo "::set-output name=changes::true"; \
          fi
      - name: Run changeset version
        if: steps.status.outputs.changes == 'true'
        run: pnpx changeset version
      - name: Reflect changeset version
        if: steps.status.outputs.changes == 'true'
        run: |
          pnpm install --frozen-lockfile false
          git commit -a --amend --no-edit
          pnpx prettier -w $(git diff --diff-filter=d --name-only HEAD~1)
          git commit -a --amend --no-edit
      # End version

      # Begin build-test-lint
      - run: pnpm build
      - run: pnpm test
      - run: pnpm lint
      - run: pnpm depcheck
      # End build-test-lint

      # Commit version
      - name: Push version commit
        if: steps.status.outputs.changes == 'true'
        # This WON'T trigger a workflow to run (using GITHUB_TOKEN).
        # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
        run: git push

      # Begin publish
      - uses: actions/checkout@v2
        with:
          clean: false
          token: ${{ secrets.MONODIST_WORKER_GITHUB_ACTIONS_PAT }}
      - name: Set npm registry authToken
        run: |
          cat << EOF > "$HOME/.npmrc"
          //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run changeset publish
        if: steps.status.outputs.changes == 'true'
        run: pnpx changeset publish
      - name: Push release git tags
        if: steps.status.outputs.changes == 'true'
        # This WILL trigger a workflow to run (using GITHUB_TOKEN).
        # To trigger a workflow, use a personal access token:
        # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
        run: git push --follow-tags
      # End publish
