name: master (push)

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: 12
  PNPM_VERSION: 5.5.12

jobs:
  changeset-build-test-run:
    runs-on: ubuntu-latest

    steps:
      # Begin setup
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          check-latest: true
          node-version: ${{ env.NODE_VERSION }}
      - name: cache pnpm-store
        id: cache-pnpm
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store
      - run: curl -L https://unpkg.com/@pnpm/self-installer | node
      - run: pnpm install
      # End setup

      # Run `prettier` before changeset
      - run: pnpm prettier

      # Begin identity
      - name: set git identity
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: set npm registry authToken
        run: |
          cat << EOF > "$HOME/.npmrc"
          //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # End identity

      # Begin changeset:version
      - name: get changeset status
        id: status
        run: |
          if pnpx changeset status 2>&1 | grep -i "no changesets present"; \
          then echo "::set-output name=changes::false"; \
          else echo "::set-output name=changes::true"; \
          fi
      - name: run changeset version
        if: steps.status.outputs.changes == 'true'
        run: pnpx changeset version
      - name: apply changeset
        if: steps.status.outputs.changes == 'true'
        run: |
          pnpm install --frozen-lockfile false
          git commit -a --amend --no-edit
          pnpx prettier -w $(git diff --diff-filter=d --name-only HEAD~1)
          git commit -a --amend --no-edit
      # End changeset:version

      # Begin standard build-test-lint workflow
      - run: pnpm build
      - run: pnpm test
      - run: pnpm lint
      - run: pnpm depcheck
      # End standard build-test-lint workflow

      # Begin changeset:publish
      - name: run changeset publish
        if: steps.status.outputs.changes == 'true'
        run: pnpx changeset publish
      - name: git push updates
        if: steps.status.outputs.changes == 'true'
        # This WON'T trigger a workflow to run (using GITHUB_TOKEN).
        # To trigger a workflow, use a personal access token:
        # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
        run: git push --follow-tags
        env:
          NPM_CONFIG_VERBOSE: 1
      # End changeset:publish
