name: master (pr)

on:
  pull_request:
    branches:
      - master
    types:
      - edited
      - opened
      - reopened
      - synchronize

env:
  NODE_VERSION: 12
  PNPM_VERSION: 5.5.12

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      # Begin setup
      - uses: actions/checkout@v2

      # allows us to reflect build-test-lint only on changed packages
      - run: git remote set-branches --add origin master
      - run: git fetch

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: cache pnpm-store
        id: cache-pnpm
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store
      - run: curl -L https://unpkg.com/@pnpm/self-installer | node
      - run: pnpm install
      # End setup

      # Begin: build-test-lint
      - run: pnpm prettier
      - run: pnpm build:branch
      - run: pnpm test:branch
      - run: pnpm lint:branch
      - run: pnpm depcheck:branch
      - run: pnpx changeset status
      # End: build-test-lint
