name: Node.js (PR to master)

on:
  pull_request:
    branches:
      - master
    types:
      - edited
      - opened
      - reopened
      - synchronize

env:
  PNPM_VERSION: 5.5.12

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      # Begin boilerplate
      - uses: actions/checkout@v2
      - run: git remote set-branches --add origin master
      - run: git fetch

      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: cache pnpm-store
        id: cache-pnpm
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ matrix.node-version }}-pnpm-store

      - run: curl -L https://unpkg.com/@pnpm/self-installer | node
      - run: pnpm install --frozen-lockfile
      - run: pnpm prettier
      - run: pnpm build:branch
      - run: pnpm test:branch
      - run: pnpm lint:branch
      - run: pnpm depcheck:branch

  changeset:
    if: github.head_ref != 'refs/heads/changeset-release/master'
    needs: build-test-lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      # Begin boilerplate
      - uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can
          # generate changelogs with the correct commits
          fetch-depth: 0
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: cache pnpm-store
        id: cache-pnpm
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ matrix.node-version }}-pnpm-store

      - run: curl -L https://unpkg.com/@pnpm/self-installer | node
      - run: pnpm install -r

      - name: ensure
        run: pnpx changeset status
