name: "Pull Request (branch: master)"

on:
  pull_request:
    branches:
      - master
    types:
      - edited
      - opened
      - reopened
      - synchronize

env:
  NODE_VERSION: 12
  PNPM_VERSION: 5.5.12

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      # Begin setup
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          check-latest: true
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache pnpm-store
        id: cache-pnpm
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store
      - run: curl -L https://unpkg.com/@pnpm/self-installer | node
      - run: pnpm install
      # End setup

      # Fetch master for delta checks
      - name: Fetch master
        # allows us to reflect build-test-lint only on changed packages
        run: |
          git remote set-branches --add origin master
          git fetch

      # Begin: build-test-lint
      - run: pnpm prettier
      - name: Build
        run: pnpm build:ancestor
      - name: Test
        run: pnpm test:ancestor
      - name: Lint
        run: pnpm lint:ancestor
      - name: Check dependencies
        run: pnpm depcheck:ancestor
      # End: build-test-lint
