name: "Dispatch (tag: @monodist/lib-b)"

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - run: echo version was was ${{ github.event.inputs.version }}
      - uses: actions/checkout@v2
        with:
          ref: refs/tags/@monodist/lib-b@${{ github.event.inputs.version }}
      - run: echo $(git rev-parse HEAD)
